### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by oysteinxyz** [svelte-view-engine/sve-app#1]
How to reproduce:
- clone repo
- npm i
- npm start

When visiting localhost:3000 it shows this

> Error: Command failed:  			node 			C:\svelte-view-engine-sve-app/scripts/svelte/build.js 			
> 
> '{"name":"_500","path":"C:\\svelte-view-engine-sve-app/src/pages/error/500.html","buildPath":"C:\\svelte-view-engine-sve-app\\build\\pages\\error\\500.html.json","useCache":false,"options":{"dir":"C:\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\svelte-view-engine-sve-app/build/pages","template":"C:\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":7669,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}'
> 
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

I also get about 9000 lines of errors in the terminal

**Comment by user896724** [comment]
I've never tried this on Windows (and don't have a machine to test) so I think this will be a compatibility thing.  If the json file in build/pages is invalid then it might be the `writeJson` call to the flowfs module (which is also not tested on Windows).  Could you post the console errors (or some of them) and the contents of build/pages/error/500.html.json?

**Comment by oysteinxyz** [comment]
Why is the repo so complex? Pug is 2 lines of code, here it's closer to 500 lines.

Here is my terminal:
> svelte-view-engine-sve-app> npm start
> 
> \> sve-app@1.0.0 start C:\svelte-view-engine-sve-app
> \> node src/main.js
> 
> Build next: error\404.html
> error\404.html: scheduling build
> Scheduling error\404.html       
> Building:
>     - error\404.html
> error\404.html: awaiting build  
> Build next: error\500.html      
> error\500.html: scheduling build
> Scheduling error\500.html
> Building:
>     - error\500.html
> error\500.html: awaiting build
> Build next: Index.html
> Index.html: scheduling build
> Scheduling Index.html
> Building:
>     - Index.html
> Index.html: awaiting build
> Page error\404.html failed, checking queue
> Error: Command failed:                          node                    C:\svelte-view-engine-sve-app/scripts/svelte/build.js                    '{"name":"_404","path":"C:\\svelte-view-engine-sve-app\\src\\pages\\error\\404.html","buildPath":"C:\\svelte-view-engine-sve-app\\build\\pages\\error\\404.html.json","useCache":false,"options":{"dir":"C:\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\svelte-view-engine-sve-app/build/pages","template":"C:\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}'
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: ` \t\t\tnode \t\t\tC:\\svelte-view-engine-sve-app/scripts/svelte/build.js \t\t\t'{"name":"_404","path":"C:\\\\svelte-view-engine-sve-app\\\\src\\\\pages\\\\error\\\\404.html","buildPath":"C:\\\\svelte-view-engine-sve-app\\\\build\\\\pages\\\\error\\\\404.html.json","useCache":false,"options":{"dir":"C:\\\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\\\svelte-view-engine-sve-app/build/pages","template":"C:\\\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}' \t\t`,
>   stdout: '',
>   stderr: "SyntaxError: Unexpected token ' in JSON at position 0\n" +
>     '    at JSON.parse (<anonymous>)\n' +
>     '    at C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:14:12\n' +
>     '    at Object.<anonymous> (C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:40:3)\n' +
>     '    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n' +
>     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n' +
>     '    at Module.load (internal/modules/cjs/loader.js:986:32)\n' +
>     '    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n' +
>     '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n' +
>     '    at internal/main/run_main_module.js:17:47\n'
> }
> Page error\404.html finished, checking queue
> (node:6212) UnhandledPromiseRejectionWarning: Error: Command failed:                    node                   C:\svelte-view-engine-sve-app/scripts/svelte/build.js                     '{"name":"_404","path":"C:\\svelte-view-engine-sve-app\\src\\pages\\error\\404.html","buildPath":"C:\\svelte-view-engine-sve-app\\build\\pages\\error\\404.html.json","useCache":false,"options":{"dir":"C:\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\svelte-view-engine-sve-app/build/pages","template":"C:\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}'
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> (node:6212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:6212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Page Index.html failed, checking queue
> Error: Command failed:                          node                    C:\svelte-view-engine-sve-app/scripts/svelte/build.js                    '{"name":"Index","path":"C:\\svelte-view-engine-sve-app\\src\\pages\\Index.html","buildPath":"C:\\svelte-view-engine-sve-app\\build\\pages\\Index.html.json","useCache":false,"options":{"dir":"C:\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\svelte-view-engine-sve-app/build/pages","template":"C:\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}'
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: ` \t\t\tnode \t\t\tC:\\svelte-view-engine-sve-app/scripts/svelte/build.js \t\t\t'{"name":"Index","path":"C:\\\\svelte-view-engine-sve-app\\\\src\\\\pages\\\\Index.html","buildPath":"C:\\\\svelte-view-engine-sve-app\\\\build\\\\pages\\\\Index.html.json","useCache":false,"options":{"dir":"C:\\\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\\\svelte-view-engine-sve-app/build/pages","template":"C:\\\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}' \t\t`,  stdout: '',
>   stderr: "SyntaxError: Unexpected token ' in JSON at position 0\n" +
>     '    at JSON.parse (<anonymous>)\n' +
>     '    at C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:14:12\n' +
>     '    at Object.<anonymous> (C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:40:3)\n' +
>     '    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n' +
>     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n' +
>     '    at Module.load (internal/modules/cjs/loader.js:986:32)\n' +
>     '    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n' +
>     '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n' +
>     '    at internal/main/run_main_module.js:17:47\n'
> }
> Page Index.html finished, checking queue
> Page error\500.html failed, checking queue
> Error: Command failed:                          node                    C:\svelte-view-engine-sve-app/scripts/svelte/build.js                    '{"name":"_500","path":"C:\\svelte-view-engine-sve-app\\src\\pages\\error\\500.html","buildPath":"C:\\svelte-view-engine-sve-app\\build\\pages\\error\\500.html.json","useCache":false,"options":{"dir":"C:\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\svelte-view-engine-sve-app/build/pages","template":"C:\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}'
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: ` \t\t\tnode \t\t\tC:\\svelte-view-engine-sve-app/scripts/svelte/build.js \t\t\t'{"name":"_500","path":"C:\\\\svelte-view-engine-sve-app\\\\src\\\\pages\\\\error\\\\500.html","buildPath":"C:\\\\svelte-view-engine-sve-app\\\\build\\\\pages\\\\error\\\\500.html.json","useCache":false,"options":{"dir":"C:\\\\svelte-view-engine-sve-app/src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"C:\\\\svelte-view-engine-sve-app/scripts/svelte/build.js","buildDir":"C:\\\\svelte-view-engine-sve-app/build/pages","template":"C:\\\\svelte-view-engine-sve-app/src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":21132,"verbose":true,"saveJs":true,"saveCss":true,"jsPrefix":"","transpile":false,"minify":false,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":true,"renderBeforeInit":true,"clientCss":true,"assetsPrefix":"/assets/"}}' \t\t`,
>   stdout: '',
>   stderr: "SyntaxError: Unexpected token ' in JSON at position 0\n" +
>     '    at JSON.parse (<anonymous>)\n' +
>     '    at C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:14:12\n' +
>     '    at Object.<anonymous> (C:\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:40:3)\n' +
>     '    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n' +
>     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n' +
>     '    at Module.load (internal/modules/cjs/loader.js:986:32)\n' +
>     '    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n' +
>     '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n' +
>     '    at internal/main/run_main_module.js:17:47\n'
> }
> Page error\500.html finished, checking queue

**Comment by user896724** [comment]
Partly because the Svelte build process is part of the project instead of being baked into svelte-view-engine, but also there was a bunch of structure left over as I copied it from a real project.  I've trimmed it down to a minimal setup now.

The .json file will be most useful in debugging - need to see why it starts with `'`.

**Comment by oysteinxyz** [comment]
Do you mean package.json? It's the same as the repo.

vscode syntax errors in template.html not sure if it matters
<img src="https://user-images.githubusercontent.com/59795195/85221268-c3dfdc00-b3b2-11ea-9747-84cf6d239104.png" width="200"/>

To be clear this renders an interactive svelte app right? You can use javascript and stores etc...

terminal errors now:
> svelte-view-engine-sve-app> npm start
> 
> \> sve-app@1.0.0 start C:\svelte-view-engine-sve-app
> \> node src/main.js
> 
> Build next: Index.html
> Index.html: scheduling build
> Scheduling Index.html
> Building:
>     - Index.html
> Index.html: awaiting build
> Page Index.html failed, checking queue
> Error: Command failed:                          node                    C:\svelte-view-engine-sve-app\src/../scripts/svelte/build.js                       '{"name":"Index","path":"\\svelte-view-engine-sve-app\\src\\pages\\Index.html","buildPath":"\\svelte-view-engine-sve-app\\build\\pages\\Index.html.json","useCache":false,"options":{"dir":"\\svelte-view-engine-sve-app\\src/../src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"\\svelte-view-engine-sve-app\\src/../scripts/svelte/build.js","buildDir":"\\svelte-view-engine-sve-app\\src/../buil    '    at \\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:14:12\n' 
> +
>     '    at Object.<anonymous> (\\svelte-view-engine-sve-app\\scripts\\svelte\\build.js:40:3)\n' +
>     '    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n' +
>     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n' +
>     '    at Module.load (internal/modules/cjs/loader.js:986:32)\n' +
>     '    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n' +
>     '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n' +
>     '    at internal/main/run_main_module.js:17:47\n'
> }
> Page Index.html finished, checking queue
> (node:6544) UnhandledPromiseRejectionWarning: Error: Command failed:                    node                    C:\svelte-view-engine-sve-app\src/../scripts/svelte/build.js                       '{"name":"Index","path":"\\svelte-view-engine-sve-app\\src\\pages\\Index.html","buildPath":"\\svelte-view-engine-sve-app\\build\\pages\\Index.html.json","useCache":false,"options":{"dir":"\\svelte-view-engine-sve-app\\src/../src/pages","type":"html","init":true,"build":false,"buildConcurrency":8,"buildScript":"\\svelte-view-engine-sve-app\\src/../scripts/svelte/build.js","buildDir":"\\svelte-view-engine-sve-app\\src/../build/pages","template":"\\svelte-view-engine-sve-app\\src/../src/template.html","payloadFormat":"json","watch":true,"liveReload":true,"liveReloadPort":10669,"verbose":true,"saveJs":true,"saveCss":true,"assetsPrefix":"/assets/","transpile":false,"minify":true,"excludeLocals":["_locals","settings","cache"],"dev":true,"stores":null,"rebuildOnRenderError":false,"renderBeforeInit":false,"clientCss":true}}' 
> SyntaxError: Unexpected token ' in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at C:\svelte-view-engine-sve-app\scripts\svelte\build.js:14:12
>     at Object.<anonymous> (C:\svelte-view-engine-sve-app\scripts\svelte\build.js:40:3)
>     at Module._compile (internal/modules/cjs/loader.js:1138:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> (node:6544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:6544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by user896724** [comment]
No I mean the .json file that gets created by the build process, at build/pages/Index.html.json.  The errors are about it being invalid JSON.  Syntax error is fine, it's just the placeholder syntax.  My editor doesn't highlight those so didn't notice, will have a think about making it valid JS though.  Yes the app will be fully interactive, SSR is just an extra.

**Comment by oysteinxyz** [comment]
Seems it crashes before it can create the build folder. Certainly invalid if it does not exist.

**Comment by user896724** [comment]
Ahh I see what's going on now, the JSON passed to the build script comes with literal quotes for some reason, must be to do with different shell syntax on Windows.  I've just pushed a change that might fix it.

**Comment by user896724** [comment]
https://github.com/svelte-view-engine/sve-app/commit/e884e409c1257c72b6ea03e3bf0f6d68da1e073d

**Comment by oysteinxyz** [comment]
Still getting JSON error at line 19 in build.js

**Comment by oysteinxyz** [comment]
Why are there two build scripts, one for dom and one for SSR? What's the difference between the two and how are they used?

How would I go about making a super minimal build script? Without payload, babel, or sass. Just the bare necessities.

**Comment by user896724** [comment]
The build script just needs to create a json file with the following structure:

```
{
    "server": {
		"cache": null, // optional bundle.cache from svelte build
        "component": "[ssr module code]",
        "css": {
            "code": "[css]",
            "map": null, // optional
        }
    },
    "client": {
		"cache": null, // optional bundle.cache from svelte build
        "js": {
            "code": "[clientside code in var Component = function() {...} form]"
        },
        "watchFiles": [
            // list of files to watch for changes to rebuild this page in dev
        ]
    }
}
```

Other than that it's up to you how you implement it, so the question of creating a minimal build is really about the svelte library.  Any working svelte build will work with svelte-view-engine as long as you output it to this structure.  The contract between you and svelte-view-engine is that you tell it the path to a build script (scripts/svelte/build.js) and svelte-view-engine calls it and passes the JSON as an argument, and expects it to create the above JSON file structure in response.  The splitting up into buildDomComponent and buildSsrComponent is just how I decided to factor the code.

**Comment by user896724** [comment]
^ The error is still about passing a json string as a command line argument then, which I'm not sure how to do on windows.  there's probably a simple solution if you wanted to do some digging, try logging yargs.argv._ to see what's needed for it to become valid json.  You may encounter other issues though, and just to make it clear windows isn't something I intend to officially support, so may not consider it a bug if it doesn't work.

**Comment by oysteinxyz** [comment]
console.log(yargs.argv._)
Those paths don't seem right

> {
>   name:Index,
>   path:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\src\\\\\\\\pages\\\\\\\\Index.html,
>   buildPath:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\build\\\\\\\\pages\\\\\\\\Index.html.json,
>   useCache:false,
>   options:{
>      dir:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\src/../src/pages,
>      type:html,
>      init:true,
>      build:false,
>      buildConcurrency:8,
>      buildScript:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\src/../scripts/svelte/build.js,
>      buildDir:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\src/../build/pages,
>      template:C:\\\\\\\\svelte-view-engine-sve-app\\\\\\\\src/../src/template.html,
>      payloadFormat:json,
>      watch:true,
>      liveReload:true,
>      liveReloadPort:55691,
>      verbose:true,
>      saveJs:true,
>      saveCss:true,
>      assetsPrefix:/assets/,
>      transpile:false,
>      minify:true,
>      excludeLocals:[
>         _locals,
>         settings,
>         cache
>      ],
>      dev:true,
>      stores:null,
>      rebuildOnRenderError:false,
>      renderBeforeInit:false,
>      clientCss:true
>   }
> }

**Comment by user896724** [comment]
Yeah there are a few problems there - 

- if that's the exact output of yargs.argv._ then it's a string when it should be an array and it's stripping out double quotes... i assume the newlines you've added for readability?

- there's some hard-coded path joining in the config i think, which is where the mixture of backslash and forward slash path separators comes from

i'm open to a PR but as i say, no official windows support...

**Comment by oysteinxyz** [comment]
It's the output from the terminal then formatted with extra lines yes. It's 8 \\\\\\\\ not 4 but is escaped when posted. It seems Windows and your os handle paths differently. 

Don't think I'm experienced enough to fix this with a PR. I'm looking for a simple way to SSR Svelte.

**Comment by user896724** [comment]
latest version may fix it (run npm install again to get latest version of sve) - reading json from stdin instead of command line.  still need to change the paths in main.js to use backslashes i think.

**Comment by oysteinxyz** [comment]
stdin is undefined. Did you mean stream.setEncoding("utf8"); in build.js?

After changing it to that I get a new error:

> Error: Could not resolve entry module (src\pages\C:\Users\Minimal\Documents\GitHub\svelte-view-engine-sve-app\src\pages\Index.html.html).
>
> at error (C:\svelte-view-engine-sve-app\node_modules\rollup\dist\shared\node-entry.js:5400:30)
> at C:\svelte-view-engine-sve-app\node_modules\rollup\dist\shared\node-entry.js:12199:20

**Comment by user896724** [comment]
oops yeah that should be stream.  OK so just a paths issue then.  Is this after changing paths in main.js?

**Comment by oysteinxyz** [comment]
Been trying to get the paths to work but I just keep getting seemingly infinite errors. It did build /build/pages with 3 files so at least that is working.

 This is the latest error after I thought I got it all right: 

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by oysteinxyz** [comment]
Tried running this on macOS today and get errors like this on npm start:

> Error: Cannot find module 'path/leading/to/parent/of/root-folder'

This was the newest version of the repo unchanged. What operating system are you using?

**Comment by user896724** [comment]
I use Linux Mint.  It should work on mac - what was the exact error?

**Comment by oysteinxyz** [comment]
Seems to be fixed on subsequent runs, and runs well on my mac now. 

My previous error was probably something to do with the build folder not being built yet. Maybe a race condition.

**Comment by user896724** [comment]
Hmm haven't seen that before.  Will close this issue then - let us know if you have any more issues.  Thanks

**Comment by oysteinxyz** [comment]
It's still broken on windows, if you don't want svelte-view-engine to support win that's fine. Though I'll share what I'm seeing now:

When I do this in "sve-app\src\main.js":

> let config = {
	template: './template.html',

It gives this warning: 

> Error: ENOENT: no such file or directory, open 'C:\\sve-app\template.html'

Notice it's trying to look for it in "../template.html" (2 dots) instead of "./template.html" (1 dot) as I specified in the config.

Did you also write the "flowfs" package? Not sure if it's related to paths.

**Comment by user896724** [comment]
Yeah I did, there could well be an error in there as it's also not tested on windows, but I couldn't see an obvious one.  I didn't realise you could use forward slashes on windows - is the meaning of . and / the same as on mac/linux?

**Comment by oysteinxyz** [comment]
On windows, 2 dots ("..") indicate the parent directory. One dot (".") represents the current directory itself. So it should mirror Unix.

I suspect Windows is inserting backslashes \ into the path when converting relative paths to static ones. Maybe the mixing of forward and backslashes into the path is causing problems.

**Comment by user896724** [comment]
I think you need to convert all / to \ in paths then right?  because windows will be treating / as just a character in the filename?

**Comment by oysteinxyz** [comment]
I tried using backslashes but no luck, the problem runs deeper.

Treating "./" as "../" in the config object paths allows me to "npm start" without errors and creates the build folder.

Visiting localhost:3000 gives an error(1) this JSON object(2) with some interesting paths. I formatted new lines for readability.

Error: (1)

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

I'm guessing svelte-view-engine generates "path" and "buildPath".
Looking at path and buildPath, we see it's adding extra file endings and mixing in a path before C:
You can see my original paths in the options{}

JSON object: (2)
> {
>   "name":"Index",
>   "path":"./src/pages/C:\\sve-app\\src\\pages\\Index.html.html",
>   "buildPath":"C:\\sve-app\\src\\pages\\Index.html.html.json",
>   "useCache":false,
>   "options":{
>     "dir":"./src/pages",
>     "type":"html",
>     "init":true,
>     "build":false,
>     "buildConcurrency":8,
>     "buildScript":"./scripts/svelte/build.js",
>     "buildDir":"./build/pages",
>     "template":"./src/template.html",
>     "payloadFormat":"json",
>     "watch":true,
>     "liveReload":true,
>     "liveReloadPort":7343,
>     "verbose":true,
>     "saveJs":true,
>     "saveCss":true,
>     "assetsPrefix":"/assets/",
>     "transpile":false,
>     "minify":true,
>     "excludeLocals":[
>       "_locals",
>       "settings",
>       "cache"
>     ],
>     "dev":true,
>     "stores":null,
>     "rebuildOnRenderError":false,
>     "renderBeforeInit":false,
>     "clientCss":true
>   }
> }

**Comment by user896724** [comment]
I think this probably narrows it down to flowfs then, there may be some incorrect usage of the built in path methods (path.resolve, join, etc) and assumptions about whether the file name includes an extension.  I know Windows sometimes doesn't show the extension e.g. in the file explorer, but it seems odd that there would be issues with it getting added twice on a code level...

**Comment by user896724** [comment]
I don't have time to look deeper into this at the moment unfortunately, but it seems close to working

**Comment by oysteinxyz** [comment]
I'm not sure of the differences between fs and flowfs, would it be possible to replace flowfs with fs?

**Comment by user896724** [comment]
Yeah, flowfs is just a wrapper over the builtin filesystem APIs with some utility methods, and is just one fairly short file, so you could do something like copy it (node_modules/flowfs/src/flowfs.js) into a module in the project, modify the relevant methods to they work on windows, then either leave as is or strip it down to just what you need and remove the rest

**Comment by user896724** [comment]
svelte-view-engine itself still uses flowfs, but if you can figure out what it's doing wrong on windows I'll patch it
